src/django_unicorn/urls.py
from django.urls import path, re_path

from django_unicorn import views

app_name = "django_unicorn"


urlpatterns = (
    re_path(r"message/(?P<component_name>[\w/\.-]+)", views.message, name="message"),
    path("message", views.message, name="message"),  # Only here to build the correct url in scripts.html
)

src/django_unicorn/templates/unicorn/errors.html
{% if unicorn.errors.items %}
<div class="unicorn-errors">
    <ul>
        {% for name, errors in unicorn.errors.items %}
        {% for error in errors %}
        <li class="unicorn-errors-{{ error.code }}">{{ error.message }}</li>
        {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endif %}

src/django_unicorn/templates/unicorn/scripts.html
{% load static %}

{{ MORPHER|json_script:"unicorn:settings:morpher" }}

{% if MINIFIED %}
<script src="{% static 'unicorn/js/unicorn.min.js' %}"></script>
{% comment %} <script src="../static/unicorn/js/unicorn.min.js"></script> {% endcomment %}

<script>
  const url = "{% url 'django_unicorn:message' %}";
  const morpherSettings = JSON.parse(document.getElementById("unicorn:settings:morpher").textContent);

  Unicorn.init(url, "{{ CSRF_HEADER_NAME }}", "{{ CSRF_COOKIE_NAME }}", morpherSettings);

</script>
{% else %}
<script type="module">
  import * as Unicorn from "{% static 'unicorn/js/unicorn.js' %}";
  import { getMorpher } from "{% static 'unicorn/js/morpher.js' %}";

  // Set Unicorn to the global, so it can be used by components
  window.Unicorn = Unicorn;

  const url = "{% url 'django_unicorn:message' %}";
  const morpherSettings = JSON.parse(document.getElementById("unicorn:settings:morpher").textContent);

  Unicorn.init(url, "{{ CSRF_HEADER_NAME }}", "{{ CSRF_COOKIE_NAME }}", morpherSettings);
</script>
{% endif %}