example/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from example.unicorn.components.hello_world import HelloWorldView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("example.www.urls")),
    # Include django-unicorn urls
    path("unicorn/", include("django_unicorn.urls")),
    path("test", HelloWorldView.as_view(), name="test"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/www/urls.py
from django.urls import path

from example.unicorn.components.direct_view import DirectViewView
from example.unicorn.components.redirects import RedirectsView
from example.www import views


app_name = "www"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "direct-view",
        DirectViewView.as_view(),
        name="direct-view",
    ),
    path(
        "redirects",
        RedirectsView.as_view(),
        name="redirects",
    ),
    path("<str:name>", views.template, name="template"),
]

example/books/models.py
from django.db import models


class Book(models.Model):
    TYPES = ((1, "Hardcover"), (2, "Softcover"))
    title = models.CharField(max_length=255)
    date_published = models.DateField()
    type = models.IntegerField(choices=TYPES, default=1)


class Author(models.Model):
    name = models.CharField(max_length=1024)
    books = models.ManyToManyField(Book)

example/coffee/models.py
import uuid

from django.db import models


class Flavor(models.Model):
    name = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    parent = models.ForeignKey("self", blank=True, null=True, on_delete=models.SET_NULL)
    float_value = models.FloatField(blank=True, null=True)
    decimal_value = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=2)
    uuid = models.UUIDField(default=uuid.uuid4)
    datetime = models.DateTimeField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    time = models.TimeField(blank=True, null=True)
    duration = models.DurationField(blank=True, null=True)

    def __str__(self):
        return self.name


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField()
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Favorite(models.Model):
    is_favorite = models.BooleanField(default=False)
    flavor = models.OneToOneField(Flavor, on_delete=models.CASCADE)


class Taste(models.Model):
    name = models.CharField(max_length=255)
    flavor = models.ManyToManyField(Flavor)


class Origin(models.Model):
    name = models.CharField(max_length=255)
    flavor = models.ManyToManyField(Flavor, related_name="origins")


class NewFlavor(Flavor):
    new_name = models.CharField(max_length=255)

example/electronics/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from datetime import datetime,timedelta
from django.utils.timezone import now
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey


class Board_Category(MPTTModel):
    name = models.CharField(max_length=1024)
    parent = TreeForeignKey('self',on_delete=models.CASCADE,null=True,blank=True, related_name='children')
    class MPTTMeta:
        order_insertion_by = ['name']
    def __str__(self):
        return 'BCat ' + str(self.id) + ' - ' + self.name
    class Meta:
        verbose_name = 'Board Category'
        verbose_name_plural = 'Board Categories'


class Board_Status(models.Model):
    status_name = models.CharField(
        max_length=1024)
    badge_class = models.CharField(
        max_length=45,
        default='primary',
        null=True,
        blank=True)
    custom_color = models.CharField(
        max_length=45,
        null=True,
        blank=True)
    force_custom_color = models.BooleanField(default=False)
    def __str__(self):
        return 'S' + str(self.id) + ' - ' + self.status_name
    class Meta:
        verbose_name = 'Board Status'
        verbose_name_plural = 'Board Statuses'

class Board(models.Model):
    board_name = models.CharField(max_length=1024)
    board_revision = models.FloatField(default=1)
    board_variant = models.CharField(default='A',max_length=5)
    board_category = models.ForeignKey(Board_Category,on_delete=models.PROTECT,null=True,blank=True)
    board_added_on = models.DateTimeField(default=now)
    board_added_by = models.ForeignKey(User,on_delete=models.PROTECT,related_name='related_board_added_by',null=True,blank=True)
    board_last_edited_on = models.DateTimeField(default=now)
    board_last_edited_by = models.ForeignKey(User,on_delete=models.PROTECT,related_name='related_board_last_edited_by',null=True,blank=True)
    board_status = models.ForeignKey(Board_Status,on_delete=models.PROTECT,null=True,blank=True)
    board_last_component_upload_on = models.DateTimeField(default=None, null=True, blank=True)
    board_last_component_upload_by = models.ForeignKey(User,on_delete=models.PROTECT,related_name='related_board_last_component_upload_by',null=True,blank=True)
    board_value_update_datetime = models.DateTimeField(default=None, null=True, blank=True)
    board_cover_picture = models.ForeignKey('Board_Image',on_delete=models.PROTECT,null=True,blank=True)
    board_appears_on_tania = models.BooleanField(default=False)
    board_group_visibility = models.ManyToManyField(Group, blank=True)

        
    class Meta:
        verbose_name = 'Board'
        verbose_name_plural = 'Boards'
    # def get_absolute_url(self):
    #     return reverse('board', args=[str(self.id)])


class Board_Image(models.Model):
    bi_board = models.ForeignKey(Board,on_delete=models.PROTECT,null=True,blank=True)
    bi_image = models.ImageField(upload_to='uploads/board-images/%Y/%m/%d/', blank=True, null=True)
    bi_upload_datetime = models.DateTimeField(default=now, blank=True, null=True)
    class Meta:
        verbose_name = 'Board Image'
        verbose_name_plural = 'Board Images'

example/issue_77/models.py
from django.db import models


class ObjA(models.Model):
    name = models.CharField(max_length=42)


class ObjB(models.Model):
    name = models.CharField(max_length=42)


class ObjC(models.Model):
    relA = models.ForeignKey(ObjA, on_delete=models.CASCADE, related_name="objcs")
    relB = models.ForeignKey(ObjB, on_delete=models.CASCADE, related_name="objcs")
    value = models.FloatField()

def populate():
    print("POPULATE DATABASE FOR ISSUE 77")

    try:
        a1 = ObjA.objects.create(id=1, name="A_1")
    except:
        pass

    try:
        b1 = ObjB.objects.create(id=1, name="B_1")
    except:
        pass
    try:
        b2 = ObjB.objects.create(id=2, name="B_2")
    except:
        pass

    try:
        c1 = ObjC.objects.create(id=1, relA=a1, relB=b1, value=0)
    except:
        pass
    try:
        c2 = ObjC.objects.create(id=2, relA=a1, relB=b2, value=0)
    except:
        pass

    print(ObjA.objects.all())
    print(ObjB.objects.all())
    print(ObjC.objects.all())


#populate()

example/unicorn/components/models.py
from django_unicorn.components import UnicornView
from django_unicorn.typing import QuerySetType
from typing import Optional, cast, Any

from example.coffee.models import Flavor, Taste


class ModelsView(UnicornView):
    flavor: Optional[Flavor] = None
    flavors: QuerySetType[Flavor] = cast(QuerySetType[Flavor], Flavor.objects.none())

    def mount(self):
        self.flavor = Flavor()
        self.refresh_flavors()

    def refresh_flavors(self):
        self.flavors = cast(QuerySetType[Flavor], Flavor.objects.all().order_by("-id")[:2])

    def save_flavor(self):
        if self.flavor:
            self.flavor.save()
        self.flavor = Flavor()
        self.refresh_flavors()

    def save(self, flavor_idx: int):
        flavor_data = self.flavors[flavor_idx]  # type: ignore
        flavor_data.save()

    def delete(self, flavor_to_delete: Flavor):
        flavor_to_delete.delete()
        self.refresh_flavors()

    def available_flavors(self):
        return Flavor.objects.all()

    def available_tastes(self):
        return Taste.objects.all()

    def model_typehint(self, flavor: Flavor):
        print(flavor)

    class Meta:
        javascript_exclude = ("flavor.taste_set",)

example/www/views.py
from django.http.response import Http404
from django.shortcuts import render
from django.template.exceptions import TemplateDoesNotExist
from django.views import generic


def index(request):
    return render(request, "www/index.html")


def template(request, name):
    try:
        return render(request, f"www/{name}.html", context={"example": "test"})
    except TemplateDoesNotExist:
        raise Http404

class ClassViewView(generic.TemplateView):
    template_name = "www/nested.html"

    def get_context_data(self, **kwargs):
        context = super(ClassViewView, self).get_context_data(**kwargs)

        context["example"] = "test"
        return context

example/www/templates/www/add-flavor.html
{% extends "www/base.html" %}
{% load static unicorn %}
{% block content %}
{% unicorn 'add-flavor' %}

  <!-- DataTables  & Plugins -->
  <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
  <script src="{% static 'js/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'js/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>



  <script>
    $(function () {
      refresh_dt();
      
    });

    function refresh_dt()
    {
      $("#flavor-table").DataTable({
        "responsive": true,
        "lengthChange": false,
        "autoWidth": false,
        "ordering": true,
        "info": true
      });
      alert("Datatable refreshed!");
    }
  </script>
{% endblock %}

example/www/templates/www/base.html
{% load static unicorn %}

<html>

<head>
  <title>django-unicorn examples</title>
  <link rel="stylesheet" href="{% static 'css/marx.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <style>
    #menu {
      list-style: none;
    }

    #menu li {
      display: inline;
      padding: 0 10px;
      border-left: solid 1px black;
    }

    #menu li:first-child {
      border-left: none !important;
    }

  </style>

  <script defer src="https://unpkg.com/@alpinejs/morph@3.x.x/dist/cdn.min.js"></script>
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>

  {% unicorn_scripts %}
</head>

<body>
  <main>
    {% csrf_token %}

    <h1>django-unicorn</h1>

    <ul id="menu">
      <li><a href="{% url 'www:index' %}">Index</a></li>
      <li><a href="{% url 'www:template' 'text-inputs' %}">Text inputs</a></li>
      <li><a href="{% url 'www:template' 'html-inputs' %}">HTML inputs</a></li>
      <li><a href="{% url 'www:template' 'objects' %}">Objects</a></li>
      <li><a href="{% url 'www:template' 'validation' %}">Validation</a></li>
      <li><a href="{% url 'www:template' 'polling' %}">Polling</a></li>
      <li><a href="{% url 'www:template' 'models' %}">Models</a></li>
      <li><a href="{% url 'www:template' 'nested' %}">Nested components (table)</a></li>
      <li><a href="{% url 'www:template' 'js' %}">JavaScript integration</a></li>
      <li><a href="{% url 'www:direct-view' %}">Direct View</a></li>
      <li><a href="{% url 'www:redirects' %}">Redirects</a></li>
      <li><a href="{% url 'www:template' 'wizard' %}">Wizard</a></li>
    </ul>

    {% block content %}{% endblock content %}

  </main>
</body>

</html>

example/www/templates/www/crispy.html
{% extends "www/base.html" %}
{% load unicorn %}

{% block content %}

{% unicorn 'crispy' %}

{% endblock content %}

example/www/templates/www/html-inputs.html
{% extends "www/base.html" %}
{% load unicorn %}

{% block content %}

<h2>HTML inputs</h2>

{% unicorn 'html-inputs' %}

{% unicorn 'todo' hello='world' %}

{% unicorn 'todo' hello=example %}

{% endblock content %}

example/www/templates/www/index.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Index</h2>

<button onclick="Unicorn.call('unicorn.components.hello_world.HelloWorldView', 'set_name');">
  Method call from outside of the component
</button>

<button onclick="alert(Unicorn.getReturnValue('unicorn.components.hello_world.HelloWorldView'));">
  Last return value from component
</button>

<!-- abcdf should be ignored and name will be None -->
{% unicorn 'unicorn.components.hello_world.HelloWorldView' name=abcdf %}

{% endblock content %}

example/www/templates/www/issue-244.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Issue 244</h2>

{% unicorn 'issue-244' %}

{% endblock content %}

example/www/templates/www/issue-249.html
{% extends "www/base.html" %}
{% load unicorn %}

{% block content %}

<h2>Issue 249</h2>

{% unicorn 'ddt-table' %}

{% endblock content %}

example/www/templates/www/issue_77.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Issue 77</h2>

{% unicorn 'issue-77' pk=1 %}

{% endblock content %}

example/www/templates/www/js.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>JavaScript integration</h2>

{% unicorn 'js' %}

{% endblock content %}

example/www/templates/www/model-relations.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Model Relations</h2>

{% unicorn 'model-relations' board_id=1 %}

{% endblock content %}

example/www/templates/www/objects.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Objects</h2>

{% unicorn 'objects' %}

{% endblock content %}

example/www/templates/www/text-inputs.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Text inputs</h2>

<button onclick="Unicorn.call('zxcv', 'set_name');">Method call from outside of the component</button>

{% unicorn 'text-inputs' key="asdf" %}

{% unicorn 'text-inputs' key="zxcv" %}

{% endblock content %}

example/www/templates/www/validation.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Using Django forms for validation</h2>

{% unicorn 'validation' hello="hello" %}

{% endblock content %}

example/www/templates/www/wizard.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>Wizard</h2>

{% unicorn 'wizard/wizard' %}

{% endblock content %}